'use client';

import LoginAuth from "@/components/login";
import { Provider } from 'react-redux';
import store from '@/store/store';
import { persistor } from '@/store/store';
import { PersistGate } from 'redux-persist/integration/react';

export const metadata = {
  title: 'Wealth Spring | Login',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <LoginAuth />
      </PersistGate>
    </Provider>
  )
}
